name: "Bug Report"
description: "Report an issue with the software."
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a short description of the issue."
      placeholder: "When playing a movie via the «Resume from» context menu, I get the error message «xyz»"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to reproduce the issue."
      placeholder: |
        1. Open the app.
        2. Click on a movie.
        3. The app crashes.
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System"
      description: "Specify the operating system you are using."
      placeholder: "e.g., Ubuntu 24.04"
      
  - type: input
    id: jellyfin_server_version
    attributes:
      label: "Jellyfin Server Version"
      description: "Specify the version of the Jellyfin server you're using. If you're using an unstable build, please include the commit hash."
      placeholder: "e.g., 10.9 or 10.10"
      
  - type: input
    id: kodi_version
    attributes:
      label: "Kodi Version"
      description: "Specify the Kodi version you're using."
      placeholder: "e.g., 20.0"
      
  - type: dropdown
    id: addon_mode
    attributes:
      label: "Addon Mode"
      description: "Select how you're using the addon."
      options:
        - "Please Select..."
        - "Addon-mode"
        - "Direct-path mode ('native')"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Please provide the logs."
      placeholder: "Paste your Kodi logs here..."
    validations:
      required: true

  - type: textarea
    id: server_logs
    attributes:
      label: "Server Logs"
      description: "Please provide server logs (if relevant)."
      placeholder: "Paste your server logs here..."
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Provide any other relevant information."
      placeholder: "Additional context, setup details or screenshots"
    validations:
      required: false
